### ISSUE TITLE
`jalr` needs parens

### ISSUE THREAD

**Issue by ThinkOpenly** [ThinkOpenly/sail#1]
Current assembly syntax for `jalr` (and perhaps others) does not include parentheses, implying that the representation should be:
```
jalr rd,rs1,imm
```
instead of what is expressed in examples in The RISC-V Instruction Set Manual in various examples:
```
jalr rd,imm12(ra)
```

**Comment by ThinkOpenly** [comment]
https://github.com/riscv/sail-riscv/issues/344

**Comment by Myrausman** [comment]
Hi @ThinkOpenly , I just wanted to confirm if this issue is still open. The link above suggests that it's completed

**Comment by ThinkOpenly** [comment]
> I just wanted to confirm if this issue is still open. The link above suggests that it's completed

Good catch. This issue has indeed been resolved.
