### ISSUE TITLE
Include optional operands

### ISSUE THREAD

**Issue by ThinkOpenly** [ThinkOpenly/sail#2]
Some instructions have optional operands, and these are not handled properly.
The functions which get mapped to the string with the operand (or without) are currently treated as "identity" functions and essentially ignored while the operand is preserved. The separator is generally emitted by these functions as well, so that is lost as well, leading to syntaxes like:
```
vle16.v        vd,(rs1)vm
```

These situations may require the "syntax" field resolving to a list of strings instead of the current strings with something like:
```
"syntaxes": [ "vd,(rs1)", "vd,(rs1),vm" ]
```

**Comment by snapdgn** [comment]
looking into this!

**Comment by ThinkOpenly** [comment]
I just thought of one additional piece of information needed here: the value to be used if there is no value specified. This was suggested in Slack:
```
{
  "operands": [
    { "name": "rs1", "type": "regidx", "optional": false },
    { "name": "rd", "type": "regidx", "optional": false },
    { "name": "vm", "type": "flag", "optional": true }
  ]
}
```
Modifying that to add a default value might look like:
```
{
  "operands": [
    { "name": "rs1", "type": "regidx", "optional": false },
    { "name": "rd", "type": "regidx", "optional": false },
    { "name": "vm", "type": "flag", "optional": true, default: "v0.t" }
  ]
}
```
