### ISSUE TITLE
clean up output

### ISSUE THREAD

**Issue by ThinkOpenly** [ThinkOpenly/sail#4]
Lots and lots of debug-level output (noise) is emitted to standard output, along with the JSON (signal).

It would be nice to make this debug output optional, perhaps via a command-line parameter (`--debug`?) or environment variable.

It would be nice to push the debug output to stderr, so it's easily filtered away by redirection. It appears that changing those non-essential `print_endline` calls to `prerr_endline` would go a long way.

**Comment by snapdgn** [comment]
Hello @ThinkOpenly, I've already begun looking into this, will draft a PR soon.

**Comment by ThinkOpenly** [comment]
I thought "Fixes #4" string in the commit message would automatically close this, but no.
Closing... (Will open a new issue for the first part, making the debug output optional.)
