### ISSUE TITLE
Make debug output optional

### ISSUE THREAD

**Issue by ThinkOpenly** [ThinkOpenly/sail#6]
Lots and lots of debug-level output is emitted to standard error.

It would be nice to make this debug output optional, perhaps via a command-line parameter (--debug?) or environment variable.

**Comment by snapdgn** [comment]
should we close this now?

**Comment by ThinkOpenly** [comment]
> should we close this now?

Agreed!
Fixed by c65ddd8153b6b7a88a52a082741ab9731932f563 and af24cf8d39eed4f622f84b6fc4a6404c8760ddee.
Thanks!
